apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-workflows-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-workflows-app
  template:
    metadata:
      labels:
        app: git-workflows-app
    spec:
      containers:
        - name: git-workflows-app
          image: jodawebdev/git-workflows:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
